# Generated by Django 5.1.4 on 2025-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Курьерская доставка'), ('pickup', 'Пункт самовывоза')], max_length=20, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('sbp', 'Оплата через СБП'), ('card', 'Оплата картой онлайн'), ('doli', 'Оплата долями'), ('sert', 'Подарочный сертификат')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
