# Generated by Django 5.1.4 on 2025-01-11 07:59

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categoryshop_level_categoryshop_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryshop',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='shop.categoryshop', verbose_name='Родительская категория'),
        ),
    ]
