# Generated by Django 5.1.4 on 2025-01-11 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_tovarshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarshop',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tovars', to='shop.categoryshop', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
