# Generated by Django 5.1.4 on 2025-01-11 12:20

import apps.shop.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_tovarshop_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.shop.models.get_file_image_foto, verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=1000, verbose_name='Тег ALT')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tovarshop', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('tovar',),
            },
        ),
    ]
