# Generated by Django 5.1.4 on 2025-01-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_categoryattribute_categoryfilter_tovarattributevalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovarfiltervalue',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='tovarfiltervalue',
            name='tovar',
        ),
        migrations.DeleteModel(
            name='CategoryFilter',
        ),
        migrations.DeleteModel(
            name='TovarFilterValue',
        ),
    ]
