# Generated by Django 5.1.4 on 2025-01-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_tovarfiltervalue_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovarattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='tovarattributevalue',
            name='tovar',
        ),
        migrations.DeleteModel(
            name='CategoryAttribute',
        ),
        migrations.DeleteModel(
            name='TovarAttributeValue',
        ),
    ]
