# Generated by Django 5.1.4 on 2025-01-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_tovarattributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryshop',
            name='attribute_type',
            field=models.CharField(blank=True, choices=[('dresses', 'Платья'), ('blazers', 'Жакеты и пиджаки')], max_length=50, null=True, verbose_name='Тип характеристик'),
        ),
    ]
