# Generated by Django 5.1.4 on 2025-01-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_categoryshop_attribute_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlazersAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_size', models.CharField(max_length=50, verbose_name='Размер экрана')),
                ('battery_capacity', models.CharField(max_length=50, verbose_name='Емкость аккумулятора')),
                ('camera', models.CharField(max_length=100, verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Характеристики смартфона',
                'verbose_name_plural': 'Характеристики смартфонов',
            },
        ),
        migrations.CreateModel(
            name='DressesAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagonal', models.CharField(max_length=50, verbose_name='Диагональ экрана')),
                ('ram', models.CharField(max_length=50, verbose_name='Объем оперативной памяти')),
                ('processor', models.CharField(max_length=100, verbose_name='Процессор')),
            ],
            options={
                'verbose_name': 'Характеристики ноутбука',
                'verbose_name_plural': 'Характеристики ноутбуков',
            },
        ),
    ]
