# Generated by Django 5.1.4 on 2025-01-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shop', '0012_blazersattributes_dressesattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarshop',
            name='blazers_attributes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.blazersattributes', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='tovarshop',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tovarshop',
            name='dresses_attributes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.dressesattributes', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='tovarshop',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
