# Generated by Django 5.1.4 on 2025-01-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_tovarshop_blazers_attributes_tovarshop_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovarshop',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tovarshop',
            name='object_id',
        ),
    ]
