# Generated by Django 5.1.4 on 2025-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_blazersattributes_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blazersattributes',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Емкость аккумулятора'),
        ),
        migrations.AlterField(
            model_name='blazersattributes',
            name='camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='blazersattributes',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер экрана'),
        ),
        migrations.AlterField(
            model_name='dressesattributes',
            name='diagonal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='dressesattributes',
            name='processor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='dressesattributes',
            name='ram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Объем оперативной памяти'),
        ),
    ]
