# Generated by Django 5.1.4 on 2025-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_blazersattributes_battery_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('code', models.CharField(help_text='Например, #FF0000 для красного', max_length=7, verbose_name='Код цвета (HEX)')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.RemoveField(
            model_name='dressesattributes',
            name='diagonal',
        ),
        migrations.AddField(
            model_name='dressesattributes',
            name='colors',
            field=models.ManyToManyField(blank=True, to='shop.color', verbose_name='Цвета'),
        ),
    ]
