# Generated by Django 5.1.4 on 2025-01-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_color_remove_dressesattributes_diagonal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Color',
            new_name='ColorDresses',
        ),
    ]
