# Generated by Django 5.1.4 on 2025-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_color_colordresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blazersattributes',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='blazersattributes',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='blazersattributes',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='dressesattributes',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='dressesattributes',
            name='ram',
        ),
        migrations.AddField(
            model_name='blazersattributes',
            name='fason',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фосан'),
        ),
        migrations.AddField(
            model_name='blazersattributes',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='dressesattributes',
            name='fason',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фасон'),
        ),
        migrations.AddField(
            model_name='dressesattributes',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер'),
        ),
    ]
