# Generated by Django 5.1.4 on 2025-01-15 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_blazersattributes_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorDresses',
            new_name='Color',
        ),
    ]
