# Generated by Django 5.1.4 on 2025-01-15 15:23

import apps.shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_colordresses_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarshop',
            name='zast',
            field=models.ImageField(blank=True, upload_to=apps.shop.models.get_file_image_zast, verbose_name='Фото'),
        ),
    ]
