# Generated by Django 5.1.4 on 2025-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_tovarshop_zast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код размера')),
                ('name', models.CharField(max_length=50, verbose_name='Название размера')),
            ],
        ),
        migrations.RemoveField(
            model_name='dressesattributes',
            name='size',
        ),
        migrations.AddField(
            model_name='tovarshop',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='tovarshop',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='dressesattributes',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='shop.size', verbose_name='Размеры'),
        ),
    ]
