# Generated by Django 5.1.4 on 2025-01-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_size_remove_dressesattributes_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
