# Generated by Django 5.1.4 on 2025-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovarshop',
            name='article',
            field=models.CharField(blank=True, max_length=255, verbose_name='Артикул'),
        ),
    ]
