# Generated by Django 5.1.4 on 2025-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_tovarshop_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressesattributes',
            name='colors',
            field=models.ManyToManyField(blank=True, to='shop.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='dressesattributes',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='shop.size', verbose_name='Размер'),
        ),
    ]
